### ISSUE TITLE
Integração do desempenho do usuário com a API

### ISSUE THREAD

**Issue by quaresmateo** [human-interaction-with-tecnologies/ritmo-mania#13]
Esses dados são necessários para que o sistema possa fazer a análise do desempenho do usuário.

**Todo**

- [ ] Tempo de jogo: `datetime`
- [ ] Quantidade de botões ativos: `inteiro`
- [ ] Quantidade de erros: `inteiro`
- [ ] Quantidade de acertos: `inteiro`
- [ ] Velocidade do intervalo: `float`
- [ ] Sequência máxima: `inteiro`
